[package]
name = "stellar-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stellar-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
log = "0.4.19"
env_logger = "0.6.0"
anyhow = "1.0.72"
tokio = "1.29.1"
futures = "0.3.28" # TODO remove?

stellar-import = { path = "../stellar-import" }
stellar-generator = { path = "../stellar-generator" }
