[package]
name = "stellar-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
actix-files = "0.6.2"
anyhow = "1.0.72"

log = "0.4.19"

stellar-database = { path = "../stellar-database" }
futures = "0.3.28"
rust-embed = { version = "8.0.0", features = ["include-exclude", "interpolate-folder-path"] }
mime_guess = "2.0.4"