[server]
address = "0.0.0.0"
port = 8080
connection-url = "mongodb://localhost"
data-folder = "/path/to/data"

# Open Graph Protocol https://ogp.me/
[ogp] # This section does not work yet
title = "Stellar"
description = "Courseware website"
requires-https = false
url = "http://your-domain.com/"